blank_issues_enabled: false
contact_links:
  - name: Mekanism Extras Discord / Mekanism Extras Discord 服务器
    url: https://discord.gg/cuPscDx7
    about: Join us on Discord to chat, discuss the game, and more. For bug reports, please use GitHub issues. / 加入我们的 Discord 服务器来闲聊、讨论游戏等。错误报告请使用 GitHub issues。