blank_issues_enabled: false
contact_links:
  - name: Mekanism Extras Discord / Mekanism Extras Discord 服务器
    url: https://discord.gg/zbmuDsXRDp
    about: Join us on Discord to discuss questions, bugs, and more. / 加入我们的 Discord 服务器来讨论问题、错误报告等。