modLoader="javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="Lost Myself"
description = "${mod_description}"
displayURL = "${mod_url}"
credits = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
mandatory=true
versionRange="[10.4.16]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanismgenerators"
mandatory=false
versionRange="[10.4.16]"
ordering="AFTER"
side="BOTH"

#[[dependencies.${mod_id}]]
#   modId="evolvedmekanism"
#   mandatory=false
#   versionRange="[1.1,)"
#   ordering="AFTER"
#   side="BOTH"
