name: Latest Build

on:
  push:
    branches: ['master', '1.19.2']
    paths: ['src/**', '**/*.gradle', 'gradle.properties']

concurrency:
  group: auto-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PUBLISH: ${{ !contains(github.event.commits[0].message, '[no-snapshot]') }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      SNAPSHOT: true
      CI: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # do a full checkout instead of a shallow clone of HEAD so spotless's ratchetFrom works
      - name: Setup Build
        uses: ./.github/actions/build_setup
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get Mod Version
        id: ver
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT
      - name: Version Suffix
        id: suffix
        run: echo "VERSION_SUFFIX=$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build
      - name: Rename Jars
        if: ${{ env.PUBLISH == 'true' }}
        run: for file in build/libs/*; do mv "$file" "${file/SHOT/SHOT+$(date --utc '+%Y%m%d-%H%M%S')-${{ env.VERSION_SUFFIX }}}"; done;
      - name: Upload Artifacts
        if: ${{ env.PUBLISH == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*
          if-no-files-found: error
          retention-days: 90
      - name: Changelog
        id: changelog
        if: ${{ env.PUBLISH == 'true' }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "./.github/json/config-latest${{ contains(github.ref_name, '1.19.2') && '-1.19.2' || '' }}.json"
          toTag: ${{ github.ref }}
          fetchViaCommits: true
          failOnError: false
      - name: Set Display Branch Name
        id: set_display_name
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "display_branch=1.20.1" >> $GITHUB_OUTPUT
          else
            echo "display_branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      - name: Release Latest
        if: ${{ env.PUBLISH == 'true' }}
        uses: andelf/nightly-release@46e2d5f80828ecc5c2c3c819eb31186a7cf2156c
        with:
          tag_name: latest-${{ github.ref_name }}
          name: '${{ steps.set_display_name.outputs.display_branch }}-${{ steps.ver.outputs.version}} SNAPSHOT ${{ env.VERSION_SUFFIX }}'
          prerelease: true
          body: |
            The latest build of Mekanism Extras for Minecraft ${{ github.ref_name }}.
            Please report any [issues](https://github.com/lostmyself8/Mekanism-Extras/issues).
            ${{ steps.changelog.outputs.changelog }}
          files: build/libs/*.jar
