# Runs formatting requirements
name: Java Formatting

on:
  push:
    branches: ['master', '1.19.2']
    paths: ['src/main/java/**', 'src/test/**']
  pull_request:
    paths: ['**']

concurrency:
  group: formatting-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # do a full checkout instead of a shallow clone of HEAD so spotless's ratchetFrom works
      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/main/java/**'
              - 'src/test/**'
      - name: Setup Build
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/build_setup
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Spotless Formatting Check with Gradle
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew spotlessCheck --warning-mode all
