# Manages labels on PRs before allowing merging
name: Pull Request Labels

# Checks for label once PR has been reviewed or label is applied
on:
  pull_request:
    types: [opened, labeled, unlabeled]

concurrency:
  group: pr-labels-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  labels:
    name: Label Check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # needed to utilize required-labels
    steps:
      - name: Check for Merge-Blocking Labels # blocks merge if present
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: 'do not merge, admin merge'
          exit_type: failure

      - name: Check for Required Type Labels # require at least one of these labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: 'type: feature, type: bugfix, type: refactor, type: translation, ignore changelog'
          exit_type: failure

      - name: Check for Required Release Label # require exactly one of these labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: 'release: api - X.0.0, release: major - 0.X.0, release: Patch - 0.0.X, release: stale'
          exit_type: failure
          
